# Generated by Django 3.2.9 on 2022-04-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='YandexData',
        ),
    ]
